version: "3"
services:  
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: proot
      MYSQL_DATABASE: api_test
    networks:
      compose-net:
        ipv4_address: 170.1.0.6
  
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
    ports: 
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      compose-net:
        ipv4_address: 170.1.0.7
  
networks:
  compose-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 170.1.0.0/24